import type { InboxConversation } from "@/types/inbox";

const PROPERTY_IMAGE =
  "https://a0.muscache.com/im/pictures/hosting/Hosting-1654953756803514090/original/cfe04d85-b718-438d-a74c-6bc0800a9fe4.jpeg";

export const INBOX_UNREAD_COUNT = 199;

export const MOCK_INBOX_CONVERSATIONS: InboxConversation[] = [
  {
    id: "conv-carlos",
    guestName: "Carlos",
    guestInitial: "C",
    preview: "Hola Carlos, buenas tardes. El apartamento está en el primer piso...",
    time: "21:00",
    dateRange: "15 jul - 19 jul",
    status: "open",
    statusLabel: "Abierta",
    propertyImageUrl: PROPERTY_IMAGE,
    bookingCode: "B20560322",
    platform: "AIRBNB",
    propertyName: "Exclusivo Apto2H | 5 min Laureles",
    propertyUnit: "Apto 101",
    propertyId: "706691",
    checkIn: "mié. 15 jul 26",
    checkOut: "dom. 19 jul 26",
    adults: 4,
    nights: 4,
    dueAmount: 1077173.04,
    paidAmount: 0,
    totalAmount: 1077173.04,
    currency: "COP",
    lastMessageAt: "Último mensaje: 17 may 2026 - 21:00",
    guestEmail: "Correo electrónico",
    guestPhone: "N/D",
    guestLanguage: "Español",
    estimatedArrival: "Horario estimado de llegada: 3:00 PM",
    estimatedDeparture: "Horario estimado de salida: 1:00 PM",
    notes: "Añade notas aquí",
    dateSeparator: "domingo, 17 de mayo de 2026",
    messages: [
      {
        id: "m1",
        sender: "guest",
        senderName: "Carlos",
        senderInitial: "C",
        time: "20:59",
        body: "Hola David. El apartamento está en que piso del edificio? Gracias.",
      },
      {
        id: "m2",
        sender: "host",
        senderName: "DAYDIANA",
        senderInitial: "D",
        time: "21:00",
        body:
          "Hola Carlos, buenas tardes. El apartamento está en el primer piso del edificio. Quedamos atentos.",
      },
    ],
  },
  {
    id: "conv-maryori",
    guestName: "Maryori R",
    guestInitial: "M",
    preview: "Hola Maryori, buenas tardes. El apartamento está en el primer piso...",
    time: "20:26",
    dateRange: "15 jul - 19 jul",
    status: "reserved",
    statusLabel: "Reservada",
    propertyImageUrl: PROPERTY_IMAGE,
    bookingCode: "B20560198",
    platform: "AIRBNB",
    propertyName: "Moderno Apto +Jacuzzi | Laureles",
    propertyUnit: "Apto 302",
    propertyId: "706512",
    checkIn: "mié. 15 jul 26",
    checkOut: "dom. 19 jul 26",
    adults: 2,
    nights: 4,
    dueAmount: 890000,
    paidAmount: 890000,
    totalAmount: 890000,
    currency: "COP",
    lastMessageAt: "Último mensaje: 17 may 2026 - 20:26",
    guestEmail: "Correo electrónico",
    guestPhone: "N/D",
    guestLanguage: "Español",
    estimatedArrival: "Horario estimado de llegada: 3:00 PM",
    estimatedDeparture: "Horario estimado de salida: 11:00 AM",
    notes: "Añade notas aquí",
    dateSeparator: "sábado, 17 de mayo de 2026",
    messages: [
      {
        id: "m1",
        sender: "guest",
        senderName: "Maryori R",
        senderInitial: "M",
        time: "20:10",
        body: "Buenas tardes, ¿tienen parqueadero disponible?",
      },
      {
        id: "m2",
        sender: "host",
        senderName: "DAYDIANA",
        senderInitial: "D",
        time: "20:26",
        body: "Hola Maryori, buenas tardes. Sí, el edificio cuenta con parqueadero para un vehículo.",
      },
    ],
  },
  {
    id: "conv-alton",
    guestName: "Alton",
    guestInitial: "A",
    preview: "Hola Alton, buenas tardes. El apartamento está en el primer piso...",
    time: "20:26",
    dateRange: "15 jul - 19 jul",
    status: "open",
    statusLabel: "Abierta",
    propertyImageUrl: PROPERTY_IMAGE,
    bookingCode: "B20560112",
    platform: "AIRBNB",
    propertyName: "Exclusivo Apto2H | 5 min Laureles",
    propertyUnit: "Apto 101",
    propertyId: "706691",
    checkIn: "mié. 15 jul 26",
    checkOut: "dom. 19 jul 26",
    adults: 3,
    nights: 4,
    dueAmount: 950000,
    paidAmount: 0,
    totalAmount: 950000,
    currency: "COP",
    lastMessageAt: "Último mensaje: 16 may 2026 - 20:26",
    guestEmail: "Correo electrónico",
    guestPhone: "N/D",
    guestLanguage: "Español",
    estimatedArrival: "Horario estimado de llegada: 4:00 PM",
    estimatedDeparture: "Horario estimado de salida: 12:00 PM",
    notes: "Añade notas aquí",
    dateSeparator: "viernes, 16 de mayo de 2026",
    messages: [
      {
        id: "m1",
        sender: "guest",
        senderName: "Alton",
        senderInitial: "A",
        time: "19:45",
        body: "¿El check-in es automático?",
      },
    ],
  },
  {
    id: "conv-ana",
    guestName: "Ana",
    guestInitial: "A",
    preview: "Hola Ana, buenas tardes. El apartamento está en el primer piso...",
    time: "20:26",
    dateRange: "15 jul - 19 jul",
    status: "reserved",
    statusLabel: "Reservada",
    propertyImageUrl: PROPERTY_IMAGE,
    bookingCode: "B20560088",
    platform: "AIRBNB",
    propertyName: "Moderno Apto +Jacuzzi | Laureles",
    propertyUnit: "Apto 302",
    propertyId: "706512",
    checkIn: "mié. 15 jul 26",
    checkOut: "dom. 19 jul 26",
    adults: 2,
    nights: 4,
    dueAmount: 820000,
    paidAmount: 820000,
    totalAmount: 820000,
    currency: "COP",
    lastMessageAt: "Último mensaje: 16 may 2026 - 20:26",
    guestEmail: "Correo electrónico",
    guestPhone: "N/D",
    guestLanguage: "Español",
    estimatedArrival: "Horario estimado de llegada: 2:00 PM",
    estimatedDeparture: "Horario estimado de salida: 11:00 AM",
    notes: "Añade notas aquí",
    dateSeparator: "viernes, 16 de mayo de 2026",
    messages: [],
  },
  {
    id: "conv-luis",
    guestName: "Luis",
    guestInitial: "L",
    preview: "Hola Luis, buenas tardes. El apartamento está en el primer piso...",
    time: "20:26",
    dateRange: "15 jul - 19 jul",
    status: "open",
    statusLabel: "Abierta",
    propertyImageUrl: PROPERTY_IMAGE,
    bookingCode: "B20560045",
    platform: "AIRBNB",
    propertyName: "Exclusivo Apto2H | 5 min Laureles",
    propertyUnit: "Apto 101",
    propertyId: "706691",
    checkIn: "mié. 15 jul 26",
    checkOut: "dom. 19 jul 26",
    adults: 2,
    nights: 4,
    dueAmount: 780000,
    paidAmount: 0,
    totalAmount: 780000,
    currency: "COP",
    lastMessageAt: "Último mensaje: 16 may 2026 - 20:26",
    guestEmail: "Correo electrónico",
    guestPhone: "N/D",
    guestLanguage: "Español",
    estimatedArrival: "Horario estimado de llegada: 3:00 PM",
    estimatedDeparture: "Horario estimado de salida: 1:00 PM",
    notes: "Añade notas aquí",
    dateSeparator: "viernes, 16 de mayo de 2026",
    messages: [],
  },
];
