/**
 * Workflows mínimos del Recepcionista Digital (deterministas).
 */
import type { ReceptionWorkflow } from "@/modules/digital-receptionist/types";

function wf(
  partial: Omit<ReceptionWorkflow, "organizationId" | "version"> & {
    organizationId?: string;
  },
): ReceptionWorkflow {
  return {
    organizationId: partial.organizationId ?? "",
    version: 1,
    ...partial,
  };
}

export function buildDefaultReceptionWorkflows(
  organizationId = "",
): ReceptionWorkflow[] {
  return [
    wf({
      id: "wf_booking",
      organizationId,
      key: "booking",
      name: "Reservar alojamiento",
      description: "Fechas → huéspedes → disponibilidad → confirmación",
      enabled: true,
      entryNodeId: "booking_ask_dates",
      nodes: [
        {
          id: "booking_ask_dates",
          name: "Pedir fechas",
          type: "question",
          message:
            "Perfecto, revisamos disponibilidad.\n\nNecesito:\n📅 Fecha de entrada\n📅 Fecha de salida\n👥 Número de huéspedes\n\nPuedes responder así:\nEntrada: DD de mes\nSalida: DD de mes\nN personas",
          variables: ["checkin", "checkout", "guests"],
          buttons: [],
          validations: ["has_dates_or_guests"],
          action: null,
          nextNodeId: "booking_lookup",
        },
        {
          id: "booking_lookup",
          name: "Consultar disponibilidad",
          type: "action",
          message:
            "Gracias. Estoy consultando el calendario con esos datos…",
          variables: [],
          buttons: [],
          validations: [],
          action: "search_availability",
          nextNodeId: "booking_result",
        },
        {
          id: "booking_result",
          name: "Resultado",
          type: "message",
          message:
            "Cuando tenga confirmación del sistema te indico opciones. ¿Deseas que un asesor te acompañe para cerrar la reserva?\n\n1. Sí, hablar con recepción\n2. Volver al menú",
          variables: [],
          buttons: [
            {
              id: "b_human",
              label: "Sí, hablar con recepción",
              value: "1",
              nextNodeId: "booking_transfer",
              sortOrder: 1,
            },
            {
              id: "b_menu",
              label: "Volver al menú",
              value: "2",
              nextNodeId: null,
              sortOrder: 2,
            },
          ],
          validations: [],
          action: null,
          nextNodeId: null,
        },
        {
          id: "booking_transfer",
          name: "Transferir",
          type: "transfer",
          message:
            "Entendido. Conecto tu conversación con recepción. Conservaré lo que ya compartiste.",
          variables: [],
          buttons: [],
          validations: [],
          action: "transfer_human",
          nextNodeId: null,
        },
      ],
    }),
    wf({
      id: "wf_my_reservation",
      organizationId,
      key: "my_reservation",
      name: "Ya tengo reserva",
      description: "Identificar reserva y ofrecer opciones",
      enabled: true,
      entryNodeId: "res_ask_id",
      nodes: [
        {
          id: "res_ask_id",
          name: "Identificar",
          type: "question",
          message:
            "Con gusto. Para ubicar tu reserva indícame el nombre del titular, el correo o el código de confirmación.",
          variables: ["nombre", "correo", "codigo"],
          buttons: [],
          validations: ["has_text"],
          action: "lookup_reservation",
          nextNodeId: "res_menu",
        },
        {
          id: "res_menu",
          name: "Opciones reserva",
          type: "buttons",
          message:
            "¿Qué necesitas?\n1. Ver acceso / WiFi\n2. Modificar llegada\n3. Factura / pago\n4. Hablar con recepción\n5. Volver al menú",
          variables: [],
          buttons: [
            {
              id: "r1",
              label: "Ver acceso",
              value: "1",
              nextNodeId: "res_access",
              sortOrder: 1,
            },
            {
              id: "r2",
              label: "Modificar llegada",
              value: "2",
              nextNodeId: "res_arrival",
              sortOrder: 2,
            },
            {
              id: "r3",
              label: "Factura",
              value: "3",
              nextNodeId: "res_pay",
              sortOrder: 3,
            },
            {
              id: "r4",
              label: "Hablar con recepción",
              value: "4",
              nextNodeId: "res_human",
              sortOrder: 4,
            },
            {
              id: "r5",
              label: "Menú",
              value: "5",
              nextNodeId: null,
              sortOrder: 5,
            },
          ],
          validations: [],
          action: null,
          nextNodeId: null,
        },
        {
          id: "res_access",
          name: "Acceso",
          type: "message",
          message:
            "Para enviarte WiFi o código de acceso necesito confirmar la propiedad. Un asesor te lo entrega con datos oficiales del sistema.",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "res_menu",
        },
        {
          id: "res_arrival",
          name: "Llegada",
          type: "message",
          message:
            "Anoto tu solicitud de cambio de llegada. Recepción confirma disponibilidad de horario.",
          variables: [],
          buttons: [],
          validations: [],
          action: "create_task",
          nextNodeId: "res_menu",
        },
        {
          id: "res_pay",
          name: "Pago",
          type: "message",
          message:
            "Te ayudo con factura o pago usando los datos del sistema. ¿A nombre de quién está la reserva?",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "res_menu",
        },
        {
          id: "res_human",
          name: "Humano",
          type: "transfer",
          message:
            "Te conecto con recepción. Un asesor continúa desde aquí.",
          variables: [],
          buttons: [],
          validations: [],
          action: "transfer_human",
          nextNodeId: null,
        },
      ],
    }),
    wf({
      id: "wf_stay",
      organizationId,
      key: "stay",
      name: "Estoy hospedado",
      description: "Menú de estadía",
      enabled: true,
      entryNodeId: "stay_menu",
      nodes: [
        {
          id: "stay_menu",
          name: "Menú estadía",
          type: "buttons",
          message:
            "¿En qué te ayudo durante tu estadía?\n1. WiFi\n2. Código de acceso\n3. Parqueadero\n4. Limpieza\n5. Toallas\n6. Problema habitación\n7. Recomendaciones\n8. Late checkout\n9. Hablar con recepción\n0. Menú principal",
          variables: [],
          buttons: [
            { id: "s1", label: "WiFi", value: "1", nextNodeId: "stay_wifi", sortOrder: 1 },
            { id: "s2", label: "Acceso", value: "2", nextNodeId: "stay_access", sortOrder: 2 },
            { id: "s3", label: "Parqueadero", value: "3", nextNodeId: "stay_parking", sortOrder: 3 },
            { id: "s4", label: "Limpieza", value: "4", nextNodeId: "stay_clean", sortOrder: 4 },
            { id: "s5", label: "Toallas", value: "5", nextNodeId: "stay_towels", sortOrder: 5 },
            { id: "s6", label: "Problema", value: "6", nextNodeId: "stay_issue", sortOrder: 6 },
            { id: "s7", label: "Recomendaciones", value: "7", nextNodeId: "stay_reco", sortOrder: 7 },
            { id: "s8", label: "Late checkout", value: "8", nextNodeId: "stay_late", sortOrder: 8 },
            { id: "s9", label: "Recepción", value: "9", nextNodeId: "stay_human", sortOrder: 9 },
            { id: "s0", label: "Menú", value: "0", nextNodeId: null, sortOrder: 0 },
          ],
          validations: [],
          action: null,
          nextNodeId: null,
        },
        {
          id: "stay_wifi",
          name: "WiFi",
          type: "message",
          message:
            "Con gusto. Consulto el WiFi oficial. ¿De qué propiedad es o a nombre de quién está la reserva?",
          variables: ["propiedad"],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "stay_menu",
        },
        {
          id: "stay_access",
          name: "Acceso",
          type: "message",
          message:
            "Te ayudo con el ingreso. ¿A nombre de quién está la reserva?",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "stay_menu",
        },
        {
          id: "stay_parking",
          name: "Parqueo",
          type: "message",
          message:
            "Sobre parqueadero: indícame la propiedad y te confirmo con recepción las instrucciones oficiales.",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "stay_menu",
        },
        {
          id: "stay_clean",
          name: "Limpieza",
          type: "message",
          message:
            "Entendido. ¿Para qué día y en qué propiedad necesitas la limpieza?",
          variables: [],
          buttons: [],
          validations: [],
          action: "create_task",
          nextNodeId: "stay_menu",
        },
        {
          id: "stay_towels",
          name: "Toallas",
          type: "message",
          message:
            "Anoto tu solicitud de toallas. Recepción lo gestiona en breve.",
          variables: [],
          buttons: [],
          validations: [],
          action: "create_task",
          nextNodeId: "stay_menu",
        },
        {
          id: "stay_issue",
          name: "Problema",
          type: "message",
          message:
            "Lamento el inconveniente. Describe el problema (y envía foto si puedes). Crearé una incidencia.",
          variables: [],
          buttons: [],
          validations: [],
          action: "create_incident",
          nextNodeId: "stay_menu",
        },
        {
          id: "stay_reco",
          name: "Reco",
          type: "message",
          message:
            "¿Qué te interesa?\n1. Restaurantes\n2. Cafés\n3. Farmacias\n4. Turismo\n5. Transporte\n6. Supermercados",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "stay_menu",
        },
        {
          id: "stay_late",
          name: "Late",
          type: "message",
          message:
            "Late checkout sujeto a disponibilidad. ¿Hasta qué hora lo necesitas?",
          variables: [],
          buttons: [],
          validations: [],
          action: "create_task",
          nextNodeId: "stay_menu",
        },
        {
          id: "stay_human",
          name: "Humano",
          type: "transfer",
          message:
            "Te conecto con recepción. Un asesor continúa desde aquí.",
          variables: [],
          buttons: [],
          validations: [],
          action: "transfer_human",
          nextNodeId: null,
        },
      ],
    }),
    wf({
      id: "wf_room_issue",
      organizationId,
      key: "room_issue",
      name: "Problema habitación",
      description: "Incidencia con categoría y descripción",
      enabled: true,
      entryNodeId: "issue_cat",
      nodes: [
        {
          id: "issue_cat",
          name: "Categoría",
          type: "buttons",
          message:
            "¿Qué tipo de problema es?\n1. Agua / baño\n2. Electricidad / internet\n3. Ruido\n4. Limpieza\n5. Mobiliario\n6. Otro",
          variables: ["issue_category"],
          buttons: [
            { id: "i1", label: "Agua", value: "1", nextNodeId: "issue_desc", sortOrder: 1 },
            { id: "i2", label: "Electricidad", value: "2", nextNodeId: "issue_desc", sortOrder: 2 },
            { id: "i3", label: "Ruido", value: "3", nextNodeId: "issue_desc", sortOrder: 3 },
            { id: "i4", label: "Limpieza", value: "4", nextNodeId: "issue_desc", sortOrder: 4 },
            { id: "i5", label: "Mobiliario", value: "5", nextNodeId: "issue_desc", sortOrder: 5 },
            { id: "i6", label: "Otro", value: "6", nextNodeId: "issue_desc", sortOrder: 6 },
          ],
          validations: [],
          action: null,
          nextNodeId: "issue_desc",
        },
        {
          id: "issue_desc",
          name: "Descripción",
          type: "question",
          message:
            "Cuéntame qué ocurre (y la propiedad). Si puedes, envía una foto.",
          variables: ["issue_detail"],
          buttons: [],
          validations: ["has_text"],
          action: "create_incident",
          nextNodeId: "issue_done",
        },
        {
          id: "issue_done",
          name: "Confirmación",
          type: "message",
          message:
            "Registré la incidencia y avisé a recepción. Te confirmarán el seguimiento. Escribe menú para otras opciones.",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: null,
        },
      ],
    }),
    wf({
      id: "wf_recommendations",
      organizationId,
      key: "recommendations",
      name: "Recomendaciones",
      description: "Menú de recomendaciones locales",
      enabled: true,
      entryNodeId: "reco_menu",
      nodes: [
        {
          id: "reco_menu",
          name: "Menú reco",
          type: "buttons",
          message:
            "¿Qué te interesa?\n1. Restaurantes\n2. Cafés\n3. Farmacias\n4. Turismo\n5. Transporte\n6. Supermercados\n0. Menú principal",
          variables: [],
          buttons: [
            { id: "c1", label: "Restaurantes", value: "1", nextNodeId: "reco_rest", sortOrder: 1 },
            { id: "c2", label: "Cafés", value: "2", nextNodeId: "reco_cafe", sortOrder: 2 },
            { id: "c3", label: "Farmacias", value: "3", nextNodeId: "reco_farm", sortOrder: 3 },
            { id: "c4", label: "Turismo", value: "4", nextNodeId: "reco_tour", sortOrder: 4 },
            { id: "c5", label: "Transporte", value: "5", nextNodeId: "reco_trans", sortOrder: 5 },
            { id: "c6", label: "Supermercados", value: "6", nextNodeId: "reco_super", sortOrder: 6 },
            { id: "c0", label: "Menú", value: "0", nextNodeId: null, sortOrder: 0 },
          ],
          validations: [],
          action: null,
          nextNodeId: null,
        },
        {
          id: "reco_rest",
          name: "Rest",
          type: "message",
          message:
            "Recomendaciones de restaurantes cercanos las confirma recepción según zona y horario. ¿Prefieres comida local, italiana o vegetariana?",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "reco_menu",
        },
        {
          id: "reco_cafe",
          name: "Cafe",
          type: "message",
          message:
            "Hay varias cafeterías cerca. Recepción te comparte las vigentes para tu zona.",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "reco_menu",
        },
        {
          id: "reco_farm",
          name: "Farm",
          type: "message",
          message:
            "Farmacias 24h dependen del barrio. ¿Me confirmas la propiedad para orientarte?",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "reco_menu",
        },
        {
          id: "reco_tour",
          name: "Tour",
          type: "message",
          message:
            "Planes turísticos: miradores, museos y tours. ¿Qué día te interesa?",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "reco_menu",
        },
        {
          id: "reco_trans",
          name: "Trans",
          type: "message",
          message:
            "Para transporte (Uber/taxi/aeropuerto) recepción te da indicaciones oficiales según tu check-out.",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "reco_menu",
        },
        {
          id: "reco_super",
          name: "Super",
          type: "message",
          message:
            "Supermercados cercanos varían por propiedad. Indica cuál es y te oriento.",
          variables: [],
          buttons: [],
          validations: [],
          action: null,
          nextNodeId: "reco_menu",
        },
      ],
    }),
    wf({
      id: "wf_human",
      organizationId,
      key: "human",
      name: "Hablar con recepción",
      description: "Transferencia humana",
      enabled: true,
      entryNodeId: "human_transfer",
      nodes: [
        {
          id: "human_transfer",
          name: "Transfer",
          type: "transfer",
          message:
            "Entendido. Voy a conectar tu conversación con recepción para que un asesor continúe. Conservaré lo que ya compartiste.",
          variables: [],
          buttons: [],
          validations: [],
          action: "transfer_human",
          nextNodeId: null,
        },
      ],
    }),
  ];
}
