/**
 * Guest utterance bank — Top ~100 real guest/client questions mapped to Concierge intents.
 * Additive: detection + human copy; does not replace RULES in detect.ts.
 */
import type { ConciergeIntent } from "@/modules/ai-concierge/types/intent";
import {
  guestTextMatchesExample,
  normalizeGuestTextForMatch,
} from "@/modules/ai-concierge/intent/guest-text-normalize";

export type GuestUtteranceEntry = {
  id: string;
  /** Canonical question (ES) */
  question: string;
  /** Extra phrasings for L1 match */
  examples: string[];
  intent: ConciergeIntent;
  /** Journey stage */
  stage:
    | "preventa"
    | "cierre"
    | "pre_llegada"
    | "estadia"
    | "salida"
    | "comercial";
  /** Optional domain id from conversation-domains corpus */
  domain?: string;
  /** Slots the dialogue should collect before tools */
  slots: string[];
  /** Auto-send clarifying / factual replies when facts ready */
  autoSendOk: boolean;
  /** Prefer escalate even if matched */
  escalate: boolean;
};

export const GUEST_UTTERANCE_BANK: GuestUtteranceEntry[] = [
  // —— A. Preventa (1–20)
  {
    id: "q001",
    question: "Hola / buenas",
    examples: ["hola", "buenas", "buenos dias", "buenas tardes", "hey", "hi"],
    intent: "OTHER",
    stage: "preventa",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q002",
    question: "¿Está disponible?",
    examples: [
      "esta disponible",
      "está disponible",
      "disponibilidad",
      "hay disponibilidad",
      "hay cupo",
      "tienes algo",
      "tienen algo",
      "necesito un apartamento",
      "busco alojamiento",
      "tienen habitaciones",
      "hay depto",
      "esta libre",
    ],
    intent: "DISPONIBILIDAD",
    stage: "preventa",
    domain: "disponibilidad",
    slots: ["checkIn", "checkOut", "guests"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q003",
    question: "¿Tienen depto/casa el fin de semana?",
    examples: ["fin de semana", "este finde", "para el finde"],
    intent: "DISPONIBILIDAD",
    stage: "preventa",
    slots: ["checkIn", "checkOut", "guests"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q004",
    question: "¿Cuánto cuesta la noche?",
    examples: ["cuanto cuesta", "cuánto cuesta", "precio por noche", "tarifa noche"],
    intent: "COTIZACION",
    stage: "preventa",
    slots: ["checkIn", "checkOut", "guests", "propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q005",
    question: "¿Precio para X noches?",
    examples: ["precio para", "cuanto por", "cuánto por", "para varias noches"],
    intent: "COTIZACION",
    stage: "preventa",
    slots: ["checkIn", "checkOut", "guests"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q006",
    question: "¿Incluye limpieza?",
    examples: ["incluye limpieza", "fee de limpieza", "cargo limpieza"],
    intent: "COTIZACION",
    stage: "preventa",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q007",
    question: "¿Hay descuento por semana/mes?",
    examples: ["descuento por semana", "descuento mensual", "tarifa semana"],
    intent: "DISCOUNT",
    stage: "preventa",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q008",
    question: "¿Aceptan reservas directas?",
    examples: ["reserva directa", "reservar directo", "sin airbnb"],
    intent: "RESERVA",
    stage: "preventa",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q009",
    question: "¿Cómo reservo?",
    examples: ["como reservo", "cómo reservo", "quiero reservar", "hacer reserva"],
    intent: "RESERVA",
    stage: "preventa",
    slots: ["checkIn", "checkOut", "guests"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q010",
    question: "¿Piden anticipo?",
    examples: ["anticipo", "deposito", "depósito", "abono inicial"],
    intent: "PAGO",
    stage: "preventa",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q011",
    question: "¿Métodos de pago?",
    examples: ["metodos de pago", "métodos de pago", "formas de pago", "puedo pagar con"],
    intent: "PAGO",
    stage: "preventa",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q012",
    question: "¿Cancelación flexible?",
    examples: ["cancelacion", "cancelación", "politica de cancelacion", "flexible cancel"],
    intent: "REGLAS",
    stage: "preventa",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q013",
    question: "¿Capacidad máxima?",
    examples: ["capacidad", "cuantas personas", "cuántas personas", "maximo huespedes"],
    intent: "DISPONIBILIDAD",
    stage: "preventa",
    slots: ["guests", "propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q014",
    question: "¿Cuántas habitaciones / camas?",
    examples: ["habitaciones", "camas", "cuartos", "dormitorios"],
    intent: "OTHER",
    stage: "preventa",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q015",
    question: "¿Hay parqueadero?",
    examples: ["parqueadero", "parking", "estacionamiento"],
    intent: "PARQUEADERO",
    stage: "preventa",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q016",
    question: "¿Aceptan mascotas?",
    examples: ["mascotas", "perro", "gato", "pet friendly", "aceptan perros"],
    intent: "MASCOTAS",
    stage: "preventa",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q017",
    question: "¿Se puede fumar?",
    examples: ["fumar", "se puede fumar", "zona de fumadores"],
    intent: "REGLAS",
    stage: "preventa",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q018",
    question: "¿Hay WiFi?",
    examples: ["hay wifi", "tienen wifi", "internet"],
    intent: "WIFI",
    stage: "preventa",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q019",
    question: "¿Zona segura / barrio?",
    examples: ["zona segura", "barrio", "es seguro"],
    intent: "DIRECCION",
    stage: "preventa",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q020",
    question: "¿Fotos reales / link?",
    examples: ["fotos", "link del anuncio", "airbnb link"],
    intent: "OTHER",
    stage: "preventa",
    slots: ["propertyId"],
    autoSendOk: false,
    escalate: false,
  },

  // —— B. Cierre (21–35)
  {
    id: "q021",
    question: "¿Me cotizas del … al … para N?",
    examples: ["me cotizas", "cotizacion", "cotización", "presupuesto"],
    intent: "COTIZACION",
    stage: "cierre",
    slots: ["checkIn", "checkOut", "guests"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q022",
    question: "¿Ese precio es total?",
    examples: ["precio total", "todo incluido", "es el total"],
    intent: "COTIZACION",
    stage: "cierre",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q023",
    question: "¿Hay IVA / fees?",
    examples: ["iva", "impuestos", "fees", "cargos adicionales"],
    intent: "COTIZACION",
    stage: "cierre",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q024",
    question: "¿Puedo pagar en dos partes?",
    examples: ["pagar en partes", "dos pagos", "abonos"],
    intent: "PAGO",
    stage: "cierre",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q025",
    question: "Confirmo, ¿cómo pago?",
    examples: ["confirmo", "como pago", "cómo pago", "listo confirmo"],
    intent: "PAGO",
    stage: "cierre",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q026",
    question: "Ya pagué, ¿quedó la reserva?",
    examples: ["ya pague", "ya pagué", "pague el anticipo", "quedo la reserva"],
    intent: "RESERVA",
    stage: "cierre",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q027",
    question: "¿Me envían comprobante?",
    examples: ["comprobante", "recibo de pago"],
    intent: "FACTURACION",
    stage: "cierre",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q028",
    question: "¿Puedo cambiar fechas?",
    examples: ["cambiar fechas", "modificar fechas", "mover la reserva"],
    intent: "RESERVA",
    stage: "cierre",
    slots: ["reservationId", "checkIn", "checkOut"],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q029",
    question: "¿Puedo agregar una persona?",
    examples: ["agregar persona", "una persona mas", "huésped extra"],
    intent: "RESERVA",
    stage: "cierre",
    slots: ["guests", "reservationId"],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q030",
    question: "¿Hay cuna / sofá cama?",
    examples: ["cuna", "sofa cama", "sofá cama", "cama extra"],
    intent: "OTHER",
    stage: "cierre",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q031",
    question: "¿Check-in temprano posible?",
    examples: ["check in temprano", "early check", "llegar antes"],
    intent: "EARLY_CHECKIN",
    stage: "cierre",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q032",
    question: "¿Late checkout?",
    examples: ["late checkout", "checkout tarde", "salida tarde"],
    intent: "LATE_CHECKOUT",
    stage: "cierre",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q033",
    question: "¿Código de la puerta antes?",
    examples: ["codigo de la puerta", "código de acceso", "cuando me dan el codigo"],
    intent: "TTLOCK",
    stage: "cierre",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q034",
    question: "¿Dirección exacta?",
    examples: ["direccion exacta", "dirección", "ubicacion", "ubicación"],
    intent: "DIRECCION",
    stage: "cierre",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q035",
    question: "¿Instrucciones de llegada?",
    examples: ["instrucciones de llegada", "como llegar", "cómo llegar"],
    intent: "DIRECCION",
    stage: "cierre",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },

  // —— C. Pre-llegada (36–55)
  {
    id: "q036",
    question: "¿A qué hora es el check-in?",
    examples: ["hora de check in", "hora de llegada", "a que hora checkin"],
    intent: "CHECKIN",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q037",
    question: "¿Puedo llegar a las 10 am?",
    examples: ["llegar a las", "llego temprano", "llego a las"],
    intent: "EARLY_CHECKIN",
    stage: "pre_llegada",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q038",
    question: "¿Dónde dejo las maletas si llego temprano?",
    examples: ["dejar maletas", "guardar equipaje", "luggage"],
    intent: "CHECKIN",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q039",
    question: "¿Quién me entrega?",
    examples: ["quien me entrega", "quién entrega", "me reciben"],
    intent: "CHECKIN",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q040",
    question: "¿Self check-in / caja / app?",
    examples: ["self check in", "caja fuerte", "smart lock", "app de acceso"],
    intent: "TTLOCK",
    stage: "pre_llegada",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q041",
    question: "¿Cuál es el código?",
    examples: ["cual es el codigo", "cuál es el código", "necesito el codigo", "codigo"],
    intent: "TTLOCK",
    stage: "pre_llegada",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q042",
    question: "El código no funciona",
    examples: ["codigo no funciona", "no abre", "no funciona el codigo"],
    intent: "TTLOCK",
    stage: "pre_llegada",
    slots: ["reservationId"],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q043",
    question: "¿WiFi nombre y clave?",
    examples: ["clave del wifi", "contraseña wifi", "wifi name", "red wifi", "wifi"],
    intent: "WIFI",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q044",
    question: "¿Hay agua caliente?",
    examples: ["agua caliente", "calentador"],
    intent: "OTHER",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q045",
    question: "¿Cómo enciendo el aire / calefacción?",
    examples: ["aire acondicionado", "calefaccion", "calefacción", "thermostat"],
    intent: "OTHER",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q046",
    question: "¿Dónde está el edificio / torre / apto?",
    examples: ["torre", "apartamento", "numero del apto", "edificio"],
    intent: "DIRECCION",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q047",
    question: "¿Parqueadero número / cómo entro?",
    examples: ["numero de parqueadero", "como entro al parqueadero"],
    intent: "PARQUEADERO",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q048",
    question: "¿Hay portería 24h?",
    examples: ["porteria", "portería", "vigilancia 24"],
    intent: "REGLAS",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q049",
    question: "Completé el registro de huéspedes",
    examples: ["complete el registro", "ya registre", "registro listo"],
    intent: "GUEST_REGISTRATION",
    stage: "pre_llegada",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q050",
    question: "No me llega el link de registro",
    examples: ["link de registro", "no llega el registro", "guest registration"],
    intent: "GUEST_REGISTRATION",
    stage: "pre_llegada",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q051",
    question: "¿Puedo traer visita?",
    examples: ["traer visita", "visitas", "invitar gente"],
    intent: "REGLAS",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q052",
    question: "¿Hay ruido / vecinos?",
    examples: ["ruido", "vecinos", "silencio"],
    intent: "REGLAS",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q053",
    question: "¿Supermercado cerca?",
    examples: ["supermercado", "tienda cerca", "exito cerca"],
    intent: "RESTAURANTES",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q054",
    question: "¿Taxi / Uber desde el aeropuerto?",
    examples: ["uber", "taxi", "aeropuerto", "traslado"],
    intent: "DIRECCION",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q055",
    question: "¿Hay toallas / sábanas?",
    examples: ["toallas", "sabanas", "sábanas", "ropa de cama"],
    intent: "TOALLAS",
    stage: "pre_llegada",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },

  // —— D. Estadía (56–75)
  {
    id: "q056",
    question: "No hay internet",
    examples: ["no hay internet", "wifi no funciona", "sin internet"],
    intent: "WIFI",
    stage: "estadia",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q057",
    question: "No hay agua / luz",
    examples: ["no hay agua", "no hay luz", "sin energia", "corte de luz"],
    intent: "EMERGENCY",
    stage: "estadia",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q058",
    question: "El aire no enfría",
    examples: ["aire no enfria", "aire no enfría", "ac no funciona"],
    intent: "COMPLAINT",
    stage: "estadia",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q059",
    question: "Hay una fuga",
    examples: ["fuga", "gotea", "inundacion", "inundación"],
    intent: "EMERGENCY",
    stage: "estadia",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q060",
    question: "Perdí el código",
    examples: ["perdi el codigo", "perdí el código", "olvide el codigo"],
    intent: "TTLOCK",
    stage: "estadia",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q061",
    question: "Se me trabó la puerta",
    examples: ["puerta trabada", "no puedo entrar", "quedo afuera"],
    intent: "TTLOCK",
    stage: "estadia",
    slots: ["reservationId"],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q062",
    question: "¿Dónde dejo la basura?",
    examples: ["basura", "desperdicios", "reciclaje"],
    intent: "REGLAS",
    stage: "estadia",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q063",
    question: "¿Horario de silencio?",
    examples: ["horario de silencio", "no molestar", "quiet hours"],
    intent: "REGLAS",
    stage: "estadia",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q064",
    question: "¿Puedo usar la lavadora?",
    examples: ["lavadora", "lavanderia", "lavandería"],
    intent: "LAVADORA",
    stage: "estadia",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q065",
    question: "¿Hay jabón / papel / amenities?",
    examples: ["jabon", "jabón", "papel higienico", "amenities"],
    intent: "TOALLAS",
    stage: "estadia",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q066",
    question: "Faltan toallas",
    examples: ["faltan toallas", "necesito toallas"],
    intent: "TOALLAS",
    stage: "estadia",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q067",
    question: "¿Recomiendan restaurantes?",
    examples: ["restaurantes", "donde comer", "dónde comer"],
    intent: "RESTAURANTES",
    stage: "estadia",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q068",
    question: "¿Hay delivery?",
    examples: ["delivery", "domicilios", "rappi"],
    intent: "RESTAURANTES",
    stage: "estadia",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q069",
    question: "El vecino hace ruido",
    examples: ["vecino hace ruido", "mucho ruido"],
    intent: "COMPLAINT",
    stage: "estadia",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q070",
    question: "Encontré algo roto",
    examples: ["esta roto", "está roto", "danado", "dañado"],
    intent: "COMPLAINT",
    stage: "estadia",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q071",
    question: "¿Puedo extender la estadía?",
    examples: ["extender", "una noche mas", "quedarme mas dias"],
    intent: "RESERVA",
    stage: "estadia",
    slots: ["checkOut", "reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q072",
    question: "¿Late checkout mañana?",
    examples: ["late checkout manana", "salir mas tarde manana"],
    intent: "LATE_CHECKOUT",
    stage: "estadia",
    slots: ["reservationId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q073",
    question: "Llega alguien más a dormir",
    examples: ["alguien mas", "huésped adicional", "otra persona"],
    intent: "REGLAS",
    stage: "estadia",
    slots: ["guests"],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q074",
    question: "¿Cómo contacto emergencia?",
    examples: ["emergencia", "urgente", "ayuda inmediata"],
    intent: "EMERGENCY",
    stage: "estadia",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q075",
    question: "Me siento mal / necesito ayuda",
    examples: ["me siento mal", "necesito ayuda medica", "ambulancia"],
    intent: "EMERGENCY",
    stage: "estadia",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },

  // —— E. Salida (76–88)
  {
    id: "q076",
    question: "¿A qué hora checkout?",
    examples: ["hora de checkout", "hora de salida", "a que hora salgo"],
    intent: "CHECKOUT",
    stage: "salida",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q077",
    question: "¿Dónde dejo las llaves?",
    examples: ["dejar llaves", "donde dejo las llaves", "devolver llaves"],
    intent: "CHECKOUT",
    stage: "salida",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q078",
    question: "¿Dejo las toallas en…?",
    examples: ["dejo las toallas", "donde dejo toallas"],
    intent: "CHECKOUT",
    stage: "salida",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q079",
    question: "Olvidé algo en el apto",
    examples: ["olvide algo", "dejé algo", "deje algo", "perdí algo"],
    intent: "OTHER",
    stage: "salida",
    slots: ["reservationId"],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q080",
    question: "¿Me cobran daños?",
    examples: ["cobran danos", "cobran daños", "deposito de seguridad"],
    intent: "PAGO",
    stage: "salida",
    slots: ["reservationId"],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q081",
    question: "¿Cuándo devuelven depósito?",
    examples: ["devuelven deposito", "devolucion deposito", "refund deposito"],
    intent: "REFUND",
    stage: "salida",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q082",
    question: "Quiero factura",
    examples: ["quiero factura", "necesito factura", "facturacion"],
    intent: "FACTURACION",
    stage: "salida",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q083",
    question: "El cobro está mal",
    examples: ["cobro mal", "me cobraron de mas", "error en el pago"],
    intent: "PAGO",
    stage: "salida",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q084",
    question: "Quiero reembolso",
    examples: ["quiero reembolso", "reembolso", "devolver dinero"],
    intent: "REFUND",
    stage: "salida",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q085",
    question: "La limpieza no fue buena",
    examples: ["limpieza mala", "no estaba limpio", "sucio"],
    intent: "COMPLAINT",
    stage: "salida",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q086",
    question: "Quiero volver / re-reservar",
    examples: ["quiero volver", "reservar de nuevo", "otra vez"],
    intent: "RESERVA",
    stage: "salida",
    slots: ["checkIn", "checkOut", "guests"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q087",
    question: "¿Me dejan reseña / link?",
    examples: ["reseña", "review", "dejar opinion"],
    intent: "OTHER",
    stage: "salida",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q088",
    question: "Gracias / todo bien",
    examples: ["gracias", "todo bien", "perfecto", "listo", "ok"],
    intent: "OTHER",
    stage: "salida",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },

  // —— F. Comercial / handoff (89–100)
  {
    id: "q089",
    question: "¿Administran mi propiedad?",
    examples: ["administran mi propiedad", "property management"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q090",
    question: "¿Cuánto cobran de comisión?",
    examples: ["comision", "comisión", "fee de administracion"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q091",
    question: "¿Cómo funciona PRAGMA?",
    examples: ["como funciona pragma", "qué es pragma"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q092",
    question: "Quiero una demo",
    examples: ["demo", "demostracion", "prueba del sistema"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q093",
    question: "¿Integran Airbnb / Booking?",
    examples: ["integran airbnb", "booking.com", "channel manager"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q094",
    question: "¿Tienen precios dinámicos?",
    examples: ["precios dinamicos", "pricelabs", "dynamic pricing"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q095",
    question: "¿Soportan multi-propiedad?",
    examples: ["multi propiedad", "varias propiedades", "portfolio"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q096",
    question: "¿Facturan a empresa?",
    examples: ["factura empresa", "nit empresa"],
    intent: "FACTURACION",
    stage: "comercial",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q097",
    question: "Hablar con un humano",
    examples: ["hablar con humano", "asesor", "agente real", "persona"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: false,
    escalate: true,
  },
  {
    id: "q098",
    question: "¿Horario de atención?",
    examples: ["horario de atencion", "horario de atención", "cuando contestan"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q099",
    question: "No es para esa propiedad",
    examples: ["propiedad equivocada", "otro apartamento", "no es esa"],
    intent: "OTHER",
    stage: "comercial",
    slots: ["propertyId"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q100",
    question: "Mensaje equivocado / spam",
    examples: ["mensaje equivocado", "perdon", "perdón", "error"],
    intent: "OTHER",
    stage: "comercial",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  // —— v2.0 informal / typo cluster (additive)
  {
    id: "q101",
    question: "Saludo informal",
    examples: ["ola", "holi", "wenas", "buenas"],
    intent: "OTHER",
    stage: "preventa",
    slots: [],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q102",
    question: "Precio informal / typo",
    examples: ["kuanto bale", "cuanto bale", "q vale", "cuanto sale"],
    intent: "COTIZACION",
    stage: "preventa",
    domain: "disponibilidad",
    slots: ["checkIn", "checkOut", "guests"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q103",
    question: "Personas typo",
    examples: ["2 persna", "2 personas", "somos 2", "para 3 pax"],
    intent: "DISPONIBILIDAD",
    stage: "preventa",
    domain: "disponibilidad",
    slots: ["guests"],
    autoSendOk: true,
    escalate: false,
  },
  {
    id: "q104",
    question: "Llegada tarde informal",
    examples: ["toq llegar tarde", "llegare tarde", "llego tarde", "llegada tarde"],
    intent: "CHECKIN",
    stage: "pre_llegada",
    domain: "checkin",
    slots: ["reservationId"],
    autoSendOk: false,
    escalate: false,
  },
  {
    id: "q105",
    question: "WiFi informal",
    examples: ["pass wifi", "clave wifi", "contrasena wifi", "internet"],
    intent: "WIFI",
    stage: "estadia",
    domain: "wifi",
    slots: ["wifiName", "wifiPassword"],
    autoSendOk: true,
    escalate: false,
  },
];

function normalize(text: string): string {
  return normalizeGuestTextForMatch(text);
}

/**
 * Match guest text against utterance bank (exact/includes + informal/typo folds).
 * Prefer longer example matches to reduce false positives.
 */
export function matchGuestUtterance(
  body: string | null | undefined,
): { entry: GuestUtteranceEntry; score: number } | null {
  const text = normalize(body ?? "");
  if (!text) return null;

  let best: { entry: GuestUtteranceEntry; score: number } | null = null;
  for (const entry of GUEST_UTTERANCE_BANK) {
    for (const example of entry.examples) {
      const ex = normalize(example);
      if (!ex) continue;
      if (guestTextMatchesExample(text, ex)) {
        const score = ex.length + (text === ex ? 50 : 10);
        if (!best || score > best.score) best = { entry, score };
      }
    }
  }
  return best;
}

export function listUtterancesByIntent(
  intent: ConciergeIntent,
): GuestUtteranceEntry[] {
  return GUEST_UTTERANCE_BANK.filter((e) => e.intent === intent);
}

export function utteranceBankStats() {
  const byIntent: Record<string, number> = {};
  for (const e of GUEST_UTTERANCE_BANK) {
    byIntent[e.intent] = (byIntent[e.intent] ?? 0) + 1;
  }
  return {
    total: GUEST_UTTERANCE_BANK.length,
    byIntent,
  };
}
